#!/usr/bin/env php
#!/usr/bin/env php
<?php

if (file_exists('./vendor/autoload.php')) {
    require './vendor/autoload.php';
} else if(file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../../bootstrap/autoload.php';
}

if (file_exists('./bootstrap/app.php')) {
    $laravel = require'./bootstrap/app.php';
} else {
    $laravel = require __DIR__.'/../../../bootstrap/app.php';
}

$commands = [
    new MarkRady\OneARTConsole\Commands\ChangeSourceNamespaceCommand(),
    new MarkRady\OneARTConsole\Commands\JobMakeCommand(),
    new MarkRady\OneARTConsole\Commands\JobDeleteCommand(),
    new MarkRady\OneARTConsole\Commands\ServiceMakeCommand(),
    new MarkRady\OneARTConsole\Commands\ServiceDeleteCommand(),
    new MarkRady\OneARTConsole\Commands\FeatureMakeCommand(),
    new MarkRady\OneARTConsole\Commands\FeatureDeleteCommand(),
    new MarkRady\OneARTConsole\Commands\ControllerMakeCommand(),
    new MarkRady\OneARTConsole\Commands\MigrationMakeCommand(),
    new MarkRady\OneARTConsole\Commands\ServicesListCommand(),
    new MarkRady\OneARTConsole\Commands\FeaturesListCommand(),

    new MarkRady\OneARTConsole\Commands\ModelMakeCommand(),
    new MarkRady\OneARTConsole\Commands\ModelDeleteCommand(),
    new MarkRady\OneARTConsole\Commands\RequestMakeCommand(),
    new MarkRady\OneARTConsole\Commands\RequestDeleteCommand(),
    new MarkRady\OneARTConsole\Commands\PolicyMakeCommand(),
    new MarkRady\OneARTConsole\Commands\PolicyDeleteCommand(),

    new MarkRady\OneARTConsole\Commands\OperationMakeCommand(),
    new MarkRady\OneARTConsole\Commands\OperationDeleteCommand(),
];

$app = new Symfony\Component\Console\Application('OneART Console', '0.1');
array_walk($commands, [$app, 'add']);

$app->run();
